Update Swate manual core features and delete installation guides
nfdi4plants/nfdi4plants.knowledgebase pull request #411
Opened 2024-04-29 14:38 UTC by StellaEggels

Deleted the Swate installation guides and updated the Core Features guides of the Swate Manual to Swate alpha.
@Freymaurer 
#403

2024-04-30 09:03 UTC, Freymaurer requested changes
Thanks a lot for your work @StellaEggels ! I really appreciate it!

2024-04-30 09:03 UTC, Freymaurer commented on src/docs/SwateManual/Docs03-Building-Blocks.md
>  ---
In addition i really like the styling in this image:
https://github.com/nfdi4plants/nfdi4plants.knowledgebase/blob/6c4aca9cb91dc0c9f62f3547fe28b5e9fd04347a/src/docs/img/Swate_a_overview2.png

Maybe we could use a unified styling for markers and arrows

2024-04-30 09:03 UTC, Freymaurer commented on src/docs/img/Swate_a_relatedtermsearch.png
Again maybe use the styling from the overview image

2024-05-02 08:12 UTC, StellaEggels commented
@Freymaurer I made the changes you suggested and changed the isa-json guide to WIP. If you agree, then please merge.

2024-05-02 10:05 UTC, Freymaurer requested changes
Thanks for the changes done! A few more things, then it is ready to merge 🙂

2024-05-02 14:16 UTC, Freymaurer approved these changes

2024-05-03 06:19 UTC, merged